# Generated by Django 5.2.11 on 2026-07-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='employment_status',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Self Employed', 'Self Employed'), ('Student', 'Student'), ('Unemployed', 'Unemployed')], default='Employed', max_length=30),
        ),
    ]
