# Generated by Django 5.2.11 on 2026-07-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanapplication_address_loanapplication_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
