# Generated by Django 5.2.11 on 2026-07-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loanapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='ai_tip',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='eligibility',
            field=models.IntegerField(default=0),
        ),
    ]
